import { execFileSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';
import { readRepoFile } from './source-helpers.js';

function extractById(source, id) {
    const marker = `id="${id}"`;
    const start = source.indexOf(marker);
    expect(start, `${id} should exist`).toBeGreaterThan(-1);
    const sectionStart = source.lastIndexOf('<section', start);
    const sectionEnd = source.indexOf('</section>', start);
    expect(sectionStart, `${id} section start should exist`).toBeGreaterThan(-1);
    expect(sectionEnd, `${id} section end should exist`).toBeGreaterThan(sectionStart);
    return source.slice(sectionStart, sectionEnd + '</section>'.length);
}

describe('English /en entry', () => {
    it('keeps generated en/index.html in sync with index.html', () => {
        execFileSync(process.execPath, ['scripts/generate-en-entry.js', '--check'], {
            cwd: process.cwd(),
            stdio: 'pipe'
        });
    });

    it('has English SEO metadata and root asset base', () => {
        const source = readRepoFile('en/index.html');
        expect(source).toContain('Generated by scripts/generate-en-entry.js');
        expect(source).toContain('<html lang="en">');
        expect(source).toContain('<base href="/">');
        expect(source).toContain('<link rel="canonical" href="https://habitschool.web.app/en">');
        expect(source).toContain('<link rel="alternate" hreflang="ko" href="https://habitschool.web.app/">');
        expect(source).toContain('<link rel="alternate" hreflang="en" href="https://habitschool.web.app/en">');
        expect(source).toContain('<meta property="og:image" content="https://habitschool.web.app/icons/og-image-en.png">');
        expect(source).toContain('<link rel="manifest" href="/manifest-en.json">');
        expect(source).toContain('"inLanguage": "en"');
    });

    it('keeps the public English landing copy English except the Korean language switch', () => {
        const source = readRepoFile('index.html');
        const landing = extractById(source, 'english-public-page');
        const withoutAllowedKoreanSwitch = landing.replaceAll('한국어', '');
        expect(withoutAllowedKoreanSwitch).not.toMatch(/[\u3131-\u318E\uAC00-\uD7A3]/);
        expect(landing).toContain('Better habits, one day at a time.');
        expect(landing).toContain('Start with Google');
        expect(landing).toContain('gBSyaStmtQI');
        expect(landing).toContain('Doctors0');
    });

    it('configures Firebase Hosting for clean English URLs', () => {
        const firebaseConfig = JSON.parse(readRepoFile('firebase.json'));
        const hosting = firebaseConfig.hosting[0];
        const redirects = hosting.redirects.map((item) => [item.source, item.destination, item.type]);
        const rewrites = hosting.rewrites.map((item) => [item.source, item.destination]);

        expect(hosting.cleanUrls).toBe(true);
        expect(hosting.trailingSlash).toBe(false);
        expect(redirects).toContainEqual(['/en/', '/en', 301]);
        expect(redirects).toContainEqual(['/en/index.html', '/en', 301]);
        expect(redirects).toContainEqual(['/en/privacy.html', '/en/privacy', 301]);
        expect(redirects).toContainEqual(['/en/terms.html', '/en/terms', 301]);
        expect(rewrites).toContainEqual(['/en', '/en/index.html']);
        expect(rewrites).toContainEqual(['/en/privacy', '/en/privacy.html']);
        expect(rewrites).toContainEqual(['/en/terms', '/en/terms.html']);
    });

    it('publishes English manifest, sitemap, and service-worker offline assets', () => {
        const manifest = JSON.parse(readRepoFile('manifest-en.json'));
        const sitemap = readRepoFile('sitemap.xml');
        const sw = readRepoFile('sw.js');

        expect(manifest.lang).toBe('en');
        expect(manifest.start_url).toBe('/en');
        expect(manifest.id).toBe('/en');
        expect(manifest.screenshots.map((item) => item.src)).toContain('icons/og-image-en.png');
        expect(sitemap).toContain('<loc>https://habitschool.web.app/en</loc>');
        expect(sitemap).toContain('<loc>https://habitschool.web.app/en/privacy</loc>');
        expect(sitemap).toContain('<loc>https://habitschool.web.app/en/terms</loc>');
        expect(sw).toContain("const EN_INDEX_URL = new URL('./en/index.html', self.location).href;");
        expect(sw).toContain("'./manifest-en.json'");
        expect(sw).toContain("'./icons/og-image-en.png'");
    });
});

// 예전에는 /en 이 로그아웃 상태일 때만 소개 페이지를 보여 줬다. 그래서
//  - 소개 페이지를 가리킬 안정적인 주소가 없었고(외국 포털 유입에 필요하다),
//  - 영어 사용자는 한글판과 달리 동의 체크박스가 있는 로그인 화면을 볼 수 없었다.
describe('English landing has its own address', () => {
    const indexSource = readRepoFile('index.html');
    const appMode = readRepoFile('js/app-mode.js');
    const enStyles = readRepoFile('styles-en.css');
    const firebaseConfig = JSON.parse(readRepoFile('firebase.json'));

    it('routes /en/welcome to the entry document', () => {
        const rewrites = firebaseConfig.hosting[0].rewrites.map((r) => r.source);
        expect(rewrites).toContain('/en/welcome');
        const redirects = firebaseConfig.hosting[0].redirects.map((r) => r.source);
        expect(redirects).toContain('/en/welcome/');
    });

    it('shows the landing by address rather than by being signed out', () => {
        expect(appMode).toContain("const ENGLISH_LANDING_PATH = '/en/welcome';");
        expect(appMode).toContain("doc.documentElement?.classList.toggle('en-landing', routeContext.isEnglishLanding);");
        expect(enStyles).toContain('html.en-landing .english-public-page');
        expect(enStyles).toContain('html:not(.en-landing) .english-public-page');
        // 로그인 여부로 랜딩을 가르던 규칙은 사라진다.
        expect(enStyles).not.toContain('html.locale-en.signed-out .english-public-page');
        expect(enStyles).not.toContain('html.locale-en.signed-out .app-container');
    });

    it('decides the landing before first paint so it does not flash the app', () => {
        expect(indexSource).toContain("normalizedPath === '/en/welcome'");
        expect(indexSource).toContain("document.documentElement.classList.add('en-landing');");
    });

    it('sends the landing CTA to the screen that carries the consent boxes', () => {
        const landing = indexSource.slice(
            indexSource.indexOf('id="english-public-page"'),
            indexSource.indexOf('</section>', indexSource.indexOf('en-hero-actions'))
        );
        expect(landing).toContain('<a class="en-google-cta" href="/en">');
        // 소개 페이지에서 바로 로그인시키면 동의를 건너뛴다.
        expect(landing).not.toContain('startEnglishGoogleSignIn');
    });
});
